### ISSUE TITLE
`fmt::Display` trait support

### ISSUE THREAD

**Issue by ivanstepanovftw** [clitic/formatx.rs#1]
I have been testing my [i18nx](https://github.com/ivanstepanovftw/i18nx) crate until I realized that  `fmt::Display` trait is not supported by formatx.

**Comment by clitic** [comment]
> Only types which implements [Display](https://doc.rust-lang.org/std/fmt/trait.Display.html) + [Debug](https://doc.rust-lang.org/std/fmt/trait.Debug.html) traits are supported.

@ivanstepanovftw Does your types implements `Debug` trait ?

**Comment by ivanstepanovftw** [comment]
No. Deriving Debug trait resolves my issue, thanks!

By the way, is it possible to support Display trait without Debug?

**Comment by clitic** [comment]
All basic types like strings and numbers implement Debug trait. If debug trait is removed then you won't be able to use `{:?}` syntax which might be a limitation in few cases.
