### ISSUE TITLE
Error with variable decimal floats "{.*f}"

### ISSUE THREAD

**Issue by bobbens** [clitic/formatx.rs#5]
Hello I've been trying to get it to work with variable length floats. In particular, the following code:
```rust
    println!( "{}", format!("{p:.d$}",  d=2, p=3.5) );
    println!( "{}", formatx!("{p:.d$}", d=2, p=3.5 ).unwrap() );
```
Results in the following error with formatx, while format is able to handle it without issue:
```
called `Result::unwrap()` on an `Err` value: Error { message: "precision value is not a valid usize in {p:.d$}", kind: Parse }
```
Am I missing something? Thanks,

**Comment by clitic** [comment]
See [limitations](https://github.com/clitic/formatx?tab=readme-ov-file#limitations)

**Comment by clitic** [comment]
@bobbens We now support this, see [supported syntax](https://github.com/clitic/formatx#supported-syntax).
